// model-header.mustache

// licenseInfo.mustache

/**
 * Libre Graph API
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.4
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIActivity.h
 *
 * Represents activity.
 */

#ifndef OAIActivity_H
#define OAIActivity_H

#include <QJsonObject>

#include "OAIActivity_template.h"
#include "OAIActivity_times.h"
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {
class OAIActivity_times;
class OAIActivity_template;


class OAIActivityPrivate;

class OAIActivity : public OAIObject {
public:
    OAIActivity();
    OAIActivity(const OAIActivity &other);
    OAIActivity(QString json);
    ~OAIActivity() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getId() const;
    void setId(const QString &id);
    bool is_id_Set() const;
    bool is_id_Valid() const;

    OAIActivity_times getTimes() const;
    void setTimes(const OAIActivity_times &times);
    bool is_times_Set() const;
    bool is_times_Valid() const;

    OAIActivity_template getRTemplate() const;
    void setRTemplate(const OAIActivity_template &r_template);
    bool is_r_template_Set() const;
    bool is_r_template_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();
    Q_DECLARE_PRIVATE(OAIActivity)
    QSharedPointer<OAIActivityPrivate> d_ptr;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIActivity)

#endif // OAIActivity_H
