// model-header.mustache

// licenseInfo.mustache

/**
 * Libre Graph API
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.4
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAICollection_of_users.h
 *
 * 
 */

#ifndef OAICollection_of_users_H
#define OAICollection_of_users_H

#include <QJsonObject>

#include "OAIUser.h"
#include <QList>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {
class OAIUser;


class OAICollection_of_usersPrivate;

class OAICollection_of_users : public OAIObject {
public:
    OAICollection_of_users();
    OAICollection_of_users(const OAICollection_of_users &other);
    OAICollection_of_users(QString json);
    ~OAICollection_of_users() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QList<OAIUser> getValue() const;
    void setValue(const QList<OAIUser> &value);
    bool is_value_Set() const;
    bool is_value_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();
    Q_DECLARE_PRIVATE(OAICollection_of_users)
    QSharedPointer<OAICollection_of_usersPrivate> d_ptr;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAICollection_of_users)

#endif // OAICollection_of_users_H
