// model-body.mustache

// licenseInfo.mustache

/**
 * Libre Graph API
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.4
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIInstance.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

class OAIInstancePrivate {
    friend class OAIInstance;

     QString url;
     bool url_isSet;
     bool url_isValid;

     bool primary;
     bool primary_isSet;
     bool primary_isValid;
};

OAIInstance::OAIInstance()
    : d_ptr()
{
}

OAIInstance::OAIInstance(const OAIInstance& other)
    : d_ptr(other.d_ptr)
{
}

OAIInstance::OAIInstance(QString json)
    : d_ptr(nullptr)
{
    this->fromJson(json);
}

OAIInstance::~OAIInstance() = default;

void OAIInstance::initializeModel() {
    if (d_ptr == nullptr) {
        d_ptr.reset(new OAIInstancePrivate{});

        Q_D(OAIInstance);


        d->url_isSet = false;
        d->url_isValid = false;

        d->primary_isSet = false;
        d->primary_isValid = false;
    }
}

void OAIInstance::fromJson(QString jsonString) {
    QByteArray array(jsonString.toUtf8());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIInstance::fromJsonObject(QJsonObject json) {
    initializeModel();

    Q_D(OAIInstance);

    d->url_isValid = ::OpenAPI::fromJsonValue(d->url, json[QString("url")]);
    d->url_isSet = !json[QString("url")].isNull() && d->url_isValid;

    d->primary_isValid = ::OpenAPI::fromJsonValue(d->primary, json[QString("primary")]);
    d->primary_isSet = !json[QString("primary")].isNull() && d->primary_isValid;
}

QString OAIInstance::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIInstance::asJsonObject() const {
    Q_D(const OAIInstance);
    if(!d){
        return {};
    }
    QJsonObject obj;
    if (d->url_isSet) {
        obj.insert(QString("url"), ::OpenAPI::toJsonValue(d->url));
    }
    if (d->primary_isSet) {
        obj.insert(QString("primary"), ::OpenAPI::toJsonValue(d->primary));
    }
    return obj;
}

QString OAIInstance::getUrl() const {
    Q_D(const OAIInstance);
    if(!d){
        return {};
    }
    return d->url;
}
void OAIInstance::setUrl(const QString &url) {
    Q_D(OAIInstance);
    Q_ASSERT(d);

    d->url = url;
    d->url_isSet = true;
}

bool OAIInstance::is_url_Set() const{
    Q_D(const OAIInstance);
    if(!d){
        return false;
    }

    return d->url_isSet;
}

bool OAIInstance::is_url_Valid() const{
    Q_D(const OAIInstance);
    if(!d){
        return false;
    }
    return d->url_isValid;
}

bool OAIInstance::isPrimary() const {
    Q_D(const OAIInstance);
    if(!d){
        return {};
    }
    return d->primary;
}
void OAIInstance::setPrimary(const bool &primary) {
    Q_D(OAIInstance);
    Q_ASSERT(d);

    d->primary = primary;
    d->primary_isSet = true;
}

bool OAIInstance::is_primary_Set() const{
    Q_D(const OAIInstance);
    if(!d){
        return false;
    }

    return d->primary_isSet;
}

bool OAIInstance::is_primary_Valid() const{
    Q_D(const OAIInstance);
    if(!d){
        return false;
    }
    return d->primary_isValid;
}

bool OAIInstance::isSet() const {
    Q_D(const OAIInstance);
    if(!d){
        return false;
    }
    bool isObjectUpdated = false;
    do {
        if (d->url_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (d->primary_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIInstance::isValid() const {
    Q_D(const OAIInstance);
    if(!d){
        return false;
    }
    // only required properties are required for the object to be considered valid
    return d->url_isValid && d->primary_isValid && true;
}

} // namespace OpenAPI
