// model-header.mustache

// licenseInfo.mustache

/**
 * Libre Graph API
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.4
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAISharingLink.h
 *
 * The &#x60;SharingLink&#x60; resource groups link-related data items into a single structure.  If a &#x60;permission&#x60; resource has a non-null &#x60;sharingLink&#x60; facet, the permission represents a sharing link (as opposed to permissions granted to a person or group). 
 */

#ifndef OAISharingLink_H
#define OAISharingLink_H

#include <QJsonObject>

#include "OAISharingLinkType.h"
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {


class OAISharingLinkPrivate;

class OAISharingLink : public OAIObject {
public:
    OAISharingLink();
    OAISharingLink(const OAISharingLink &other);
    OAISharingLink(QString json);
    ~OAISharingLink() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    OAISharingLinkType getType() const;
    void setType(const OAISharingLinkType &type);
    bool is_type_Set() const;
    bool is_type_Valid() const;

    bool isPreventsDownload() const;
    void setPreventsDownload(const bool &prevents_download);
    bool is_prevents_download_Set() const;
    bool is_prevents_download_Valid() const;

    QString getWebUrl() const;
    void setWebUrl(const QString &web_url);
    bool is_web_url_Set() const;
    bool is_web_url_Valid() const;

    QString getLibreGraphDisplayName() const;
    void setLibreGraphDisplayName(const QString &libre_graph_display_name);
    bool is_libre_graph_display_name_Set() const;
    bool is_libre_graph_display_name_Valid() const;

    bool isLibreGraphQuickLink() const;
    void setLibreGraphQuickLink(const bool &libre_graph_quick_link);
    bool is_libre_graph_quick_link_Set() const;
    bool is_libre_graph_quick_link_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();
    Q_DECLARE_PRIVATE(OAISharingLink)
    QSharedPointer<OAISharingLinkPrivate> d_ptr;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAISharingLink)

#endif // OAISharingLink_H
