name: Build with conan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Building ${{ matrix.build_type }} ${{ matrix.profile }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # Release build type
          - os: ubuntu-latest
            profile: ubuntu-latest-x86_64
            build_type: Release
          - os: macos-latest
            profile: macos-latest-armv8
            build_type: Release
          - os: windows-latest
            profile: windows-latest-x86_64
            build_type: Release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Conan
        uses: conan-io/setup-conan@v1

      - name: Add artifactory & set conan config
        run: |
          conan config install ./.conan/config/global.conf
          conan remote remove conancenter
          conan remote add oc https://artifactory.owncloud-demo.com/artifactory/api/conan/conan-local
          conan remote login oc ${{ secrets.CONAN_USER }} -p ${{ secrets.CONAN_PASSWORD }}
          conan remote list
          conan profile show

      - name: Build the client with conan
        run: |
          conan build . --profile=.conan/profiles/${{ matrix.profile }}.conanprofile -s build_type=${{ matrix.build_type }}

      - name: Run tests
        shell: bash
        if: runner.os != 'Linux'
        working-directory: ./build
        run: |
          ctest --output-on-failure -C ${{ matrix.build_type }}
